### ISSUE TITLE
On this page links not working

### ISSUE THREAD

**Issue by aishairzay** [onflow/next-docs-v1#581] opened 2022-08-16 21:01 UTC
Hyperlinks on right side of the following page do not work to help scroll within the page: https://developers.flow.com/cadence/language/values-and-types

**Comment by alxflw** [comment] 2022-08-17 17:52
could be the same as https://github.com/onflow/next-docs-v1/issues/588

**Comment by 10thfloor** [comment] 2022-08-17 17:53
Closing because duplicate of #588

**Closed by 10thfloor** 2022-08-17 17:53 UTC
Labels: p-high
