### ISSUE TITLE
Ensure relative linking works between different markdown and mdx documents

### ISSUE THREAD

**Issue by schpet** [onflow/next-docs-v1#118] opened 2022-06-07 18:39 UTC
- [ ] find and document examples of documents with relative links in different repos
- [ ] configure markdown processing or html base tags to ensure linking works between anchor tags, img elements, etc

**Comment by kerrywei** [comment] 2022-06-13 17:16
closing this as it's a duplicate of: https://github.com/onflow/next-docs-v1/issues/15 and https://github.com/onflow/next-docs-v1/issues/91

**Closed by kerrywei** 2022-06-13 17:16 UTC
